# This workflow will build a packer image and create an AMI

name: Create AMIs
on:
  # Only run manually
  workflow_dispatch: {}
env:
  AWS_REGION : "eu-central-1"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/packer_role
          role-session-name: github-packer-session-role
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-packer@v3

      - name: Build AMI
        id: build
        run: packer build -var 'skip_create_ami=false' packer/docker.pkr.hcl
